language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo check --verbose --all
  - cargo test --verbose --all
  - cargo build --verbose --all
