language: rust

sudo: required

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo install cargo-kcov
  - cargo check --verbose
  - cargo test --verbose
  - cargo kcov --verbose
  - cargo build --verbose

env:
  - CODECOV_TOKEN="b367470e-4733-49aa-931d-ecbf28bcf838"

addons:
  apt:
    packages:
      - kcov

after_success: |
  for file in target/debug/adf-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"